### ISSUE TITLE
Relax 1.7 not working on ColdFusion 8

### ISSUE THREAD

**Issue by ignandis** [ColdBox/coldbox-relax#30]
Tried to install Relax module against ColdFusion 8 and get the following error messages right of the bat.

ColdFusion was looking at the following text:
eventPattern

The CFML compiler was processing:

A script statement beginning with function on line 93, column 9.
A cfscript tag beginning on line 12, column 2.
 
 
The error occurred in C:\_projects\CFBuilder\relaxApp\modules\relax\ModuleConfig.cfc: line 93

**Comment by lmajano** [comment]
cf8 is deprecated
