### ISSUE TITLE
Relax 2.0 not compatible with CF9

### ISSUE THREAD

**Issue by wphampton** [ColdBox/coldbox-relax#34]
Though [the documentation states](https://github.com/ColdBox/coldbox-relax#system-requirements) that Relax requires ColdFusion 9+ it doesn't seem that Relax 2.x is compatible with CF9 out of the box.

**Relax.DSL.cfc** uses the CF9 reserved word 'default' in various places:   
```java
function globalHeader(
  required string name,
  string description="",
  boolean required=false,
  string default="",
  string type="string"
){
   ...
 }
```

**DSLDoc.cfc** uses arrayEach which isn't available until CF10 to my knowledge:

```java
arrayEach( md.functions, function( thisMD ){
  arrayAppend( aSortedNames, arguments.thisMD.name );
  mdLookup[ arguments.thisMD.name ] = arguments.thisMD;
});
```
Possibly some other items I haven't gotten to yet but I wanted to reach out to the community to see if I am missing something?

Thanks!
Wes

**Comment by wphampton** [comment]
Just saw @gratzc has submitted Pull Request #33 back in May to address this.  +1 for accepting that.  Thanks Curt!

**Comment by lmajano** [comment]
I believe this is done
